apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "k8s-onboarding.fullname" . }}
  labels:
    app: {{ template "k8s-onboarding.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end -}}