apiVersion: v2
name: shinyproxy
description: A Helm chart to deplo ShinyProxy (https://www.shinyproxy.io/)

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.2.0

dependencies:
- name: library-chart
  version: 1.5.23
  repository: https://inseefrlab.github.io/helm-charts-interactive-services
