proxyDeploy:
  image:
    name: openanalytics/shinyproxy
    tag: 3.0.2
    pullPolicy: Always
  replicaCount: 1
  resources: 
    limits:
      cpu: 2000m
      memory: "10000Mi"
    requests:
      cpu: "1000m"
      memory: "5000Mi"
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: 
    # fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  securityContext: 
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  nodeSelector: {}
  tolerations: []
  affinity: {}

proxyConfig:
  landingPage: /
  heartbeatRate: 10000
  heartbeatTimeout: 60000
  containerWaitTime: 20000
  port: 8080
  authentication:
    #type: none
     type: openid
     openid:
      authURL: 	"https://auth.insee.fr/auth/realms/insee-datascience/protocol/openid-connect/auth"
      tokenURL: "https://auth.insee.fr/auth/realms/insee-datascience/protocol/openid-connect/token"
      jwksURL: "https://auth.insee.fr/auth/realms/insee-datascience/protocol/openid-connect/certs"
      clientCredentialsSecretName: moncredentialsecret
      usernameAttribute: preferred_username
      rolesClaim : groups
    #   tokenURL: ""
    #   jwksURL: ""
    #   logoutURL: ""
    #   usernameAttribute: ""
    #   rolesClaim: ""
    #   clientCredentialsSecretName: ""

apps:
  - id: "helloWOrld"
    display-name: "helloW"
    description: "on dit bonjour"
    container-image: "gitlab-registry.insee.fr/datascience/registry-prod-custom/shiny-hello-world-docker-image:0.0.3"
    container-cmd: []
    access-groups: []
    container-memory-limit: 1000Mi
    container-cpu-limit: 200m
    max-lifetime: 1
    container-env:
      toto: 
      tutu: tutu
  - id: "helloworld2"
    display-name: "le second monde "
    description: "rien "
    container-image: "gitlab-registry.insee.fr/datascience/registry-prod-custom/shiny-hello-world-docker-image:0.0.3"
    container-cmd: []
    access-groups: []
    container-memory-limit: 1000Mi
    container-cpu-limit: 200m
    max-lifetime: 1 
    container-env:
      pwdapps2:
      userapps2:


secretApps:
  name: mesSecretsApps


ingress:
  enabled: true
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx-rdp
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  hostname: monshinyproxy.qf-datascience.kube.insee.fr

service:
    type: ClusterIP
    port: 8080

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
