apiVersion: v2
name: census
description: A Helm chart for mariaDB and maweb
type: application
version: 0.1.0
dependencies:
  - name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 10.3.2
