apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "addok.fullname" . }}
  labels:
    {{- include "addok.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "addok.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "addok.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: conf
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: addok.conf
                path: addok.conf
        {{- toYaml .Values.volumes.addokDataVolume | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "addok.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.init.enabled }}
      initContainers:
        - name: download-data
          image: {{ .Values.init.image | quote }}
          command: {{- range .Values.init.command }}
          - {{ . | quote }}
          {{- end }}
          args: {{- range .Values.init.args }} 
          - {{ . | quote }}
          {{- end }}
          {{- if .Values.init.env }}
          env: 
            {{- range $key, $val := .Values.init.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          {{- end}}
          volumeMounts:
            - mountPath: /data
              name: data          
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WORKERS
              value: {{ .Values.workers | quote }}
            - name: WORKER_TIMEOUT
              value: {{ .Values.workerTimeout | quote }}
            - name: REDIS_HOST
              value: {{ include "addok.redis.fullname" . | quote }}
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - mountPath: /etc/addok/addok.conf
              subPath: addok.conf
              name: conf
            - mountPath: /data
              name: data  
          ports:
            - name: http
              containerPort: 7878
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /search?q=18+boulevard+Adolphe+Pinard+paris
              port: http
          readinessProbe:
            httpGet:
              path: /search?q=18+boulevard+Adolphe+Pinard+paris
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
