apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fauxpilot.fullnameTriton" . }}
  labels:
    {{- include "fauxpilot.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fauxpilot.selectorLabelsTriton" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fauxpilot.selectorLabelsTriton" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fauxpilot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.triton.repository }}:{{ .Values.image.triton.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.triton.pullPolicy }}
          command:
            - sh
            - -c
            - |
              wget -q  https://minio.lab.sspcloud.fr/mbenxsalha/diffusion/fauxpilot/{{ .Values.model }}.zip && \
              apt-get update && apt-get install -y zip  && \
              unzip -q {{ .Values.model }}.zip  -d ../ && \
              mv /{{ .Values.model }}/huggingface  /root/.cache && \
              mv /{{ .Values.model }} /model && \
              rm {{ .Values.model }}.zip && \ 
              CUDA_VISIBLE_DEVICES=0 mpirun -n 1 --allow-run-as-root /opt/tritonserver/bin/tritonserver --model-repository=/model
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: grpc
              containerPort: 8001
            - name: metrics
              containerPort: 8002
          livenessProbe:
            httpGet:
              path: /v2/health/ready
              port: http
            initialDelaySeconds: 150
          readinessProbe:
            httpGet:
              path: /v2/health/ready
              port: http
            initialDelaySeconds: 150
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
