apiVersion: v1
kind: Service
metadata:
  name: {{ include "onyxia.ui.fullname" . }}
  labels:
    {{- include "onyxia.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "onyxia.ui.selectorLabels" . | nindent 4 }}
