{{- $fullName := include "library-chart.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxyDeploy.replicaCount }}
  selector:
    matchLabels:
      {{- include "library-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.proxyDeploy.podAnnotations | nindent 8 }}
      labels:
        {{- include "library-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: shinyproxy
          image: "{{ .Values.proxyDeploy.image.name }}:{{ .Values.proxyDeploy.image.tag }}"
          imagePullPolicy: {{ .Values.proxyDeploy.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.proxyDeploy.podSecurityContext | nindent 12 }}
          volumeMounts:
            - name: shinyproxy
              mountPath: /opt/shinyproxy/application.yml
              subPath: application.yml
            {{ if  .Values.existingAppsSecretName }}
            - name: apps-secret-files
              mountPath: /opt/shinyproxy/conf
            {{ end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9090
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9090
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            initialDelaySeconds:  {{ .Values.readinessProbe.initialDelaySeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.proxyDeploy.resources | nindent 12 }}
      volumes:
        {{ if eq .Values.proxyConfig.authentication.type "none" }}
        - name: shinyproxy
          configMap:
            name: {{ include "library-chart.fullname" . }}
        {{ end }}
        {{ if eq .Values.proxyConfig.authentication.type "openid" }}
        - name: shinyproxy
          emptyDir: {}
        - name: app-conf
          configMap:
            name: {{ include "library-chart.fullname" . }}
        - name: oidc-secrets
          secret:
            secretName: {{ .Values.proxyConfig.authentication.openid.existingClientCredentialsSecretName }}
        {{ end }}
        {{ if  .Values.existingAppsSecretName }}
        - name: apps-secret-files
          secret:
            secretName: {{ .Values.existingAppsSecretName }}
        {{ end }}
      {{ if eq .Values.proxyConfig.authentication.type "openid" }}
      initContainers:
        - name: init
          image: "inseefrlab/onyxia-base:latest"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 512Mi          
          volumeMounts:
            - name: app-conf
              mountPath: /etc/app-conf/application.yml
              subPath: application.yml
            - name: oidc-secrets
              mountPath: /etc/oidc-secrets
            - name: shinyproxy
              mountPath: /etc/merge-conf
          command:
            - sh
            - -c
            - |
              
              CLIENT_ID=`cat /etc/oidc-secrets/client-id`
              CLIENT_SECRET=`cat /etc/oidc-secrets/client-secret`

              cp /etc/app-conf/application.yml /etc/merge-conf/application.yml
              sed -i "s/client-id:.*/client-id: $CLIENT_ID/" /etc/merge-conf/application.yml
              sed -i "s/client-secret:.*/client-secret: $CLIENT_SECRET/" /etc/merge-conf/application.yml

      {{- end }}
      serviceAccountName: {{ include "library-chart.serviceAccountName" . }}
      nodeSelector:
        {{- toYaml .Values.proxyDeploy.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.proxyDeploy.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.proxyDeploy.tolerations | nindent 8 }}
