apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "s3-operator.fullname" . }}-manager-role
  labels:
  {{- include "s3-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - s3.onyxia.sh
  resources:
  - buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.onyxia.sh
  resources:
  - buckets/finalizers
  verbs:
  - update
- apiGroups:
  - s3.onyxia.sh
  resources:
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - s3.onyxia.sh
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.onyxia.sh
  resources:
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - s3.onyxia.sh
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - s3.onyxia.sh
  resources:
  - paths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.onyxia.sh
  resources:
  - paths/finalizers
  verbs:
  - update
- apiGroups:
  - s3.onyxia.sh
  resources:
  - paths/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - s3.onyxia.sh
  resources:
  - s3user
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - s3.onyxia.sh
  resources:
  - s3user/finalizers
  verbs:
  - update
- apiGroups:
  - s3.onyxia.sh
  resources:
  - s3user/status
  verbs:
  - get
  - patch
  - update  
- apiGroups: [""]
  resources: [ "secrets" ]
<<<<<<< HEAD
  verbs: ["list","create" , "patch" , "update" ,"delete"]
=======
  verbs: ["create" , "patch" , "update" ,"delete"]
>>>>>>> 14129f0ea631847a40ee71cd99c2dafabbc3a378

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "s3-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: s3-operator
    app.kubernetes.io/part-of: s3-operator
  {{- include "s3-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "s3-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "s3-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'